export interface SeedBook {
  isbn: string
  title: string
  author: string
  publisher: string
  year: number
  edition: string
  category: string
  shelf: string
  pdfUrl: string
  description: string
}

export const seedBooks: SeedBook[] = [
  // ============================================================
  // COMPUTER SCIENCE (10)
  // ============================================================
  {
    isbn: "978-1-491-93936-9",
    title: "Think Python",
    author: "Allen B. Downey",
    publisher: "O'Reilly Media",
    year: 2015,
    edition: "2nd Edition",
    category: "Computer Science",
    shelf: "CS-A1",
    pdfUrl: "https://greenteapress.com/thinkpython2/thinkpython2.pdf",
    description: "An introduction to Python programming for beginners, covering fundamental computer science concepts.",
  },
  {
    isbn: "978-0-486-49820-1",
    title: "Common Lisp: A Gentle Introduction to Symbolic Computation",
    author: "David S. Touretzky",
    publisher: "Dover Publications",
    year: 2013,
    edition: "Dover Edition",
    category: "Computer Science",
    shelf: "CS-A2",
    pdfUrl: "https://www.cs.cmu.edu/~dst/LispBook/book.pdf",
    description: "A highly accessible introduction to Common Lisp programming.",
  },
  {
    isbn: "978-0-9885024-0-6",
    title: "Mathematics for Computer Science",
    author: "Eric Lehman, F. Thomson Leighton, Albert R. Meyer",
    publisher: "MIT OpenCourseWare",
    year: 2018,
    edition: "Revised Edition",
    category: "Computer Science",
    shelf: "CS-A3",
    pdfUrl: "https://courses.csail.mit.edu/6.042/spring18/mcs.pdf",
    description: "A comprehensive introduction to discrete mathematics for computer science students.",
  },
  {
    isbn: "978-1-927356-38-8",
    title: "Open Data Structures (Java Edition)",
    author: "Pat Morin",
    publisher: "AU Press",
    year: 2013,
    edition: "1st Edition",
    category: "Computer Science",
    shelf: "CS-B1",
    pdfUrl: "https://opendatastructures.org/ods-java.pdf",
    description: "An open textbook covering the design and implementation of fundamental data structures in Java.",
  },
  {
    isbn: "978-0-9716775-0-0",
    title: "How to Think Like a Computer Scientist: Learning with Python",
    author: "Allen B. Downey, Jeffrey Elkner, Chris Meyers",
    publisher: "Green Tea Press",
    year: 2002,
    edition: "1st Edition",
    category: "Computer Science",
    shelf: "CS-B2",
    pdfUrl: "https://greenteapress.com/thinkpython/thinkpython.pdf",
    description: "The original introductory programming text that spawned the Think Python series.",
  },
  {
    isbn: "978-0-262-51087-5",
    title: "Structure and Interpretation of Computer Programs",
    author: "Harold Abelson, Gerald Jay Sussman, Julie Sussman",
    publisher: "MIT Press",
    year: 1996,
    edition: "2nd Edition",
    category: "Computer Science",
    shelf: "CS-C1",
    pdfUrl: "https://web.mit.edu/6.001/6.037/sicp.pdf",
    description: "The legendary MIT textbook on programming language design, abstraction, and meta-linguistic abstraction.",
  },
  {
    isbn: "978-0-201-70073-2",
    title: "Foundations of Computer Science",
    author: "Alfred V. Aho, Jeffrey D. Ullman",
    publisher: "W. H. Freeman",
    year: 1994,
    edition: "C Edition",
    category: "Computer Science",
    shelf: "CS-C2",
    pdfUrl: "http://infolab.stanford.edu/~ullman/focs.html",
    description: "Classic text covering fundamental computer science topics: data structures, automata, and algorithm analysis.",
  },
  {
    isbn: "978-1-68092-244-8",
    title: "Automate the Boring Stuff with Python",
    author: "Al Sweigart",
    publisher: "No Starch Press",
    year: 2019,
    edition: "2nd Edition",
    category: "Computer Science",
    shelf: "CS-D1",
    pdfUrl: "https://automatetheboringstuff.com/2e/automate2.pdf",
    description: "Practical Python programming for total beginners — covers automating everyday computer tasks.",
  },
  {
    isbn: "978-0-13-595705-0",
    title: "The C Programming Language",
    author: "Brian W. Kernighan, Dennis M. Ritchie",
    publisher: "Prentice Hall",
    year: 1988,
    edition: "2nd Edition",
    category: "Computer Science",
    shelf: "CS-D2",
    pdfUrl: "https://www.cs.cmu.edu/~srini/15-446/labs/k_r.pdf",
    description: "The definitive guide to C — written by the language's creators. Essential for systems programming.",
  },
  {
    isbn: "978-1-4842-1288-2",
    title: "Pro Git",
    author: "Scott Chacon, Ben Straub",
    publisher: "Apress",
    year: 2014,
    edition: "2nd Edition",
    category: "Computer Science",
    shelf: "CS-D3",
    pdfUrl: "https://git-scm.com/book/en/v2/progit2.pdf",
    description: "The official Git book — covers everything from basic version control to advanced Git internals.",
  },

  // ============================================================
  // MATHEMATICS (8)
  // ============================================================
  {
    isbn: "978-1-947172-13-5",
    title: "Calculus Volume 1",
    author: "Gilbert Strang, Edwin Herman",
    publisher: "OpenStax / Rice University",
    year: 2016,
    edition: "1st Edition",
    category: "Mathematics",
    shelf: "MATH-A1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/CalculusVolume1-OP.pdf",
    description: "Covers functions, limits, derivatives, and integration. Designed for the typical two-semester general calculus course.",
  },
  {
    isbn: "978-1-947172-14-2",
    title: "Calculus Volume 2",
    author: "Gilbert Strang, Edwin Herman",
    publisher: "OpenStax / Rice University",
    year: 2016,
    edition: "1st Edition",
    category: "Mathematics",
    shelf: "MATH-A2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/CalculusVolume2-OP.pdf",
    description: "Continues with integration techniques, differential equations, sequences, series, and parametric equations.",
  },
  {
    isbn: "978-1-947172-16-6",
    title: "Calculus Volume 3",
    author: "Gilbert Strang, Edwin Herman",
    publisher: "OpenStax / Rice University",
    year: 2016,
    edition: "1st Edition",
    category: "Mathematics",
    shelf: "MATH-A3",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/CalculusVolume3-OP.pdf",
    description: "Covers parametric equations, polar coordinates, vectors, functions of several variables, multiple integration, and second-order differential equations.",
  },
  {
    isbn: "978-1-975076-52-8",
    title: "Precalculus",
    author: "Jay Abramson",
    publisher: "OpenStax / Rice University",
    year: 2017,
    edition: "2nd Edition",
    category: "Mathematics",
    shelf: "MATH-B1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/Precalculus-OP.pdf",
    description: "Prepares students for calculus with coverage of functions, trigonometry, sequences, and analytic geometry.",
  },
  {
    isbn: "978-1-947172-12-8",
    title: "College Algebra",
    author: "Jay Abramson",
    publisher: "OpenStax / Rice University",
    year: 2015,
    edition: "2nd Edition",
    category: "Mathematics",
    shelf: "MATH-B2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/CollegeAlgebra-OP.pdf",
    description: "Comprehensive coverage of algebraic principles with real-world applications. Foundation for STEM coursework.",
  },
  {
    isbn: "978-1-975076-54-2",
    title: "Introductory Statistics",
    author: "Barbara Illowsky, Susan Dean",
    publisher: "OpenStax / Rice University",
    year: 2018,
    edition: "2nd Edition",
    category: "Mathematics",
    shelf: "MATH-C1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductoryStatistics-OP.pdf",
    description: "Introductory statistics text covering probability, distributions, hypothesis testing, regression, and ANOVA.",
  },
  {
    isbn: "978-1-975076-56-6",
    title: "Elementary Algebra",
    author: "Lynn Marecek, MaryAnne Anthony-Smith",
    publisher: "OpenStax / Rice University",
    year: 2017,
    edition: "2nd Edition",
    category: "Mathematics",
    shelf: "MATH-C2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/ElementaryAlgebra2e-OP.pdf",
    description: "Foundational algebra text covering real numbers, linear equations, polynomials, factoring, and quadratic equations.",
  },
  {
    isbn: "978-1-975076-58-0",
    title: "Intermediate Algebra",
    author: "Lynn Marecek",
    publisher: "OpenStax / Rice University",
    year: 2017,
    edition: "2nd Edition",
    category: "Mathematics",
    shelf: "MATH-C3",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/IntermediateAlgebra2e-OP.pdf",
    description: "Builds on elementary algebra covering rational expressions, radicals, quadratics, exponential and logarithmic functions.",
  },

  // ============================================================
  // PHYSICS (4)
  // ============================================================
  {
    isbn: "978-1-938168-00-0",
    title: "College Physics",
    author: "Paul Peter Urone, Roger Hinrichs",
    publisher: "OpenStax / Rice University",
    year: 2012,
    edition: "1st Edition",
    category: "Physics",
    shelf: "PHY-A1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/CollegePhysics-OP.pdf",
    description: "Introductory algebra-based physics covering mechanics, thermodynamics, waves, electricity, and modern physics.",
  },
  {
    isbn: "978-1-938168-16-1",
    title: "University Physics Volume 1",
    author: "Samuel J. Ling, William Moebs, Jeff Sanny",
    publisher: "OpenStax / Rice University",
    year: 2016,
    edition: "1st Edition",
    category: "Physics",
    shelf: "PHY-A2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume1-OP.pdf",
    description: "Calculus-based physics covering mechanics, sound, oscillations, and waves.",
  },
  {
    isbn: "978-1-938168-17-8",
    title: "University Physics Volume 2",
    author: "Samuel J. Ling, William Moebs, Jeff Sanny",
    publisher: "OpenStax / Rice University",
    year: 2016,
    edition: "1st Edition",
    category: "Physics",
    shelf: "PHY-A3",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume2-OP.pdf",
    description: "Covers electricity, magnetism, and electromagnetic waves. Calculus-based approach.",
  },
  {
    isbn: "978-1-938168-18-5",
    title: "University Physics Volume 3",
    author: "Samuel J. Ling, William Moebs, Jeff Sanny",
    publisher: "OpenStax / Rice University",
    year: 2016,
    edition: "1st Edition",
    category: "Physics",
    shelf: "PHY-A4",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume3-OP.pdf",
    description: "Covers optics and modern physics including relativity, quantum mechanics, and nuclear physics.",
  },

  // ============================================================
  // CHEMISTRY (2)
  // ============================================================
  {
    isbn: "978-1-947172-62-3",
    title: "Chemistry 2e",
    author: "Paul Flowers, Klaus Theopold, Richard Langley, William R. Robinson",
    publisher: "OpenStax / Rice University",
    year: 2019,
    edition: "2nd Edition",
    category: "Chemistry",
    shelf: "CHM-A1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/Chemistry2e-OP.pdf",
    description: "Comprehensive general chemistry textbook covering atomic structure, bonding, reactions, thermodynamics, and organic chemistry.",
  },
  {
    isbn: "978-1-938168-39-0",
    title: "Organic Chemistry",
    author: "John McMurry",
    publisher: "OpenStax / Rice University",
    year: 2023,
    edition: "1st Edition",
    category: "Chemistry",
    shelf: "CHM-A2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/OrganicChemistry-OP.pdf",
    description: "Comprehensive introduction to organic chemistry covering structure, reactivity, synthesis, and spectroscopy.",
  },

  // ============================================================
  // LIFE SCIENCES (4)
  // ============================================================
  {
    isbn: "978-1-947172-51-7",
    title: "Biology 2e",
    author: "Mary Ann Clark, Matthew Douglas, Jung Choi",
    publisher: "OpenStax / Rice University",
    year: 2018,
    edition: "2nd Edition",
    category: "Life Sciences",
    shelf: "BIO-A1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-OP.pdf",
    description: "Comprehensive introductory biology covering biochemistry, cell biology, genetics, evolution, and ecology.",
  },
  {
    isbn: "978-1-947172-03-6",
    title: "Concepts of Biology",
    author: "Samantha Fowler, Rebecca Roush, James Wise",
    publisher: "OpenStax / Rice University",
    year: 2013,
    edition: "1st Edition",
    category: "Life Sciences",
    shelf: "BIO-A2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/ConceptsBiology-OP.pdf",
    description: "Introductory biology for non-majors covering core concepts from cellular to ecosystem levels.",
  },
  {
    isbn: "978-1-947172-23-4",
    title: "Microbiology",
    author: "Nina Parker, Mark Schneegurt, Anh-Hue Thi Tu",
    publisher: "OpenStax / Rice University",
    year: 2016,
    edition: "1st Edition",
    category: "Life Sciences",
    shelf: "BIO-B1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/Microbiology-OP.pdf",
    description: "Comprehensive microbiology text covering prokaryotes, eukaryotes, viruses, microbial genetics, and immunology.",
  },
  {
    isbn: "978-1-947172-60-9",
    title: "Biology for AP Courses",
    author: "Julianne Zedalis, John Eggebrecht",
    publisher: "OpenStax / Rice University",
    year: 2018,
    edition: "1st Edition",
    category: "Life Sciences",
    shelf: "BIO-B2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/BiologyforAPCourses-OP.pdf",
    description: "Advanced placement biology covering eight units from chemistry of life to ecology.",
  },

  // ============================================================
  // MEDICINE & HEALTH (3)
  // ============================================================
  {
    isbn: "978-1-947172-04-3",
    title: "Anatomy and Physiology",
    author: "J. Gordon Betts, Kelly A. Young, James A. Wise",
    publisher: "OpenStax / Rice University",
    year: 2022,
    edition: "2nd Edition",
    category: "Medicine",
    shelf: "MED-A1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/AnatomyandPhysiology-OP.pdf",
    description: "A comprehensive introduction to the structure and function of the human body.",
  },
  {
    isbn: "978-0-323-47731-5",
    title: "Basic Medical Microbiology",
    author: "Patrick R. Murray",
    publisher: "Elsevier",
    year: 2017,
    edition: "1st Edition",
    category: "Medicine",
    shelf: "MED-A2",
    pdfUrl: "https://www.ncbi.nlm.nih.gov/books/NBK571554/pdf/Bookshelf_NBK571554.pdf",
    description: "An introductory guide to medical microbiology covering bacteria, viruses, fungi, and parasites.",
  },
  {
    isbn: "978-1-947172-55-5",
    title: "Population Health for Health Professionals",
    author: "Denise M. Linton, Shirley K. James",
    publisher: "OpenStax / Rice University",
    year: 2022,
    edition: "1st Edition",
    category: "Medicine",
    shelf: "MED-B1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/PopulationHealth-OP.pdf",
    description: "Comprehensive guide to population health, public health systems, epidemiology, and health policy.",
  },

  // ============================================================
  // ENGINEERING (2)
  // ============================================================
  {
    isbn: "978-1-947172-56-2",
    title: "Workplace Software and Skills",
    author: "Tammie Bolling, Angela Mitchell, Tanya Scott",
    publisher: "OpenStax / Rice University",
    year: 2023,
    edition: "1st Edition",
    category: "Engineering",
    shelf: "ENG-A1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/WorkplaceSoftware-OP.pdf",
    description: "Practical guide to workplace technology covering spreadsheets, databases, presentations, and collaborative tools.",
  },
  {
    isbn: "978-1-947172-57-9",
    title: "Introduction to Computer Science",
    author: "OpenStax",
    publisher: "OpenStax / Rice University",
    year: 2024,
    edition: "1st Edition",
    category: "Engineering",
    shelf: "ENG-A2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductionComputerScience-OP.pdf",
    description: "Foundational text for computer science majors covering algorithms, data structures, and computational thinking.",
  },

  // ============================================================
  // FINANCE & BUSINESS (7)
  // ============================================================
  {
    isbn: "978-1-947172-67-8",
    title: "Financial Accounting",
    author: "Mitchell Franklin, Patty Graybeal, Dixon Cooper",
    publisher: "OpenStax / Rice University",
    year: 2019,
    edition: "1st Edition",
    category: "Finance",
    shelf: "FIN-A1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/FinancialAccounting-OP.pdf",
    description: "A rigorous introduction to financial accounting principles.",
  },
  {
    isbn: "978-1-947172-36-4",
    title: "Principles of Economics 3e",
    author: "Steven A. Greenlaw, David Shapiro, Daniel MacDonald",
    publisher: "OpenStax / Rice University",
    year: 2023,
    edition: "3rd Edition",
    category: "Finance",
    shelf: "FIN-A2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesofEconomics3e-OP.pdf",
    description: "A comprehensive introduction to microeconomics and macroeconomics with contemporary examples.",
  },
  {
    isbn: "978-1-947172-54-8",
    title: "Principles of Management",
    author: "David S. Bright, Anastasia H. Cortes",
    publisher: "OpenStax / Rice University",
    year: 2019,
    edition: "1st Edition",
    category: "Finance",
    shelf: "FIN-B1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesofManagement-OP.pdf",
    description: "Comprehensive introduction to management theory, organizational behavior, strategic planning, and leadership.",
  },
  {
    isbn: "978-1-947172-75-3",
    title: "Introduction to Business",
    author: "Lawrence J. Gitman, Carl McDaniel, Amit Shah",
    publisher: "OpenStax / Rice University",
    year: 2018,
    edition: "1st Edition",
    category: "Finance",
    shelf: "FIN-B2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductiontoBusiness-OP.pdf",
    description: "Comprehensive introduction to business covering management, marketing, finance, economics, and entrepreneurship.",
  },
  {
    isbn: "978-1-947172-70-8",
    title: "Entrepreneurship",
    author: "Michael Laverty, Chris Littel",
    publisher: "OpenStax / Rice University",
    year: 2020,
    edition: "1st Edition",
    category: "Finance",
    shelf: "FIN-C1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/Entrepreneurship-OP.pdf",
    description: "Practical guide to starting and running a business — business models, funding, marketing, and growth strategies.",
  },
  {
    isbn: "978-1-947172-76-0",
    title: "Business Law I Essentials",
    author: "Mirande Valbrune, Renee De Assis",
    publisher: "OpenStax / Rice University",
    year: 2019,
    edition: "1st Edition",
    category: "Finance",
    shelf: "FIN-C2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/BusinessLawIESSENTIALS-OP.pdf",
    description: "Introduction to legal principles in business — contracts, torts, employment law, and business organizations.",
  },
  {
    isbn: "978-1-947172-68-5",
    title: "Principles of Macroeconomics 3e",
    author: "Steven A. Greenlaw, David Shapiro, Daniel MacDonald",
    publisher: "OpenStax / Rice University",
    year: 2023,
    edition: "3rd Edition",
    category: "Finance",
    shelf: "FIN-D1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesofMacroeconomics3e-OP.pdf",
    description: "Comprehensive macroeconomics text covering GDP, inflation, unemployment, monetary and fiscal policy.",
  },

  // ============================================================
  // SOCIAL SCIENCES (5)
  // ============================================================
  {
    isbn: "978-1-947172-80-7",
    title: "Psychology 2e",
    author: "Rose M. Spielman, William J. Jenkins, Marilyn D. Lovett",
    publisher: "OpenStax / Rice University",
    year: 2020,
    edition: "2nd Edition",
    category: "Social Sciences",
    shelf: "SOC-A1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/Psychology2e-OP.pdf",
    description: "Comprehensive introduction to psychology — biological bases, cognition, development, disorders, and therapy.",
  },
  {
    isbn: "978-1-947172-11-1",
    title: "Introduction to Sociology 3e",
    author: "Tonja R. Conerly, Kathleen Holmes, Asha Lal Tamang",
    publisher: "OpenStax / Rice University",
    year: 2021,
    edition: "3rd Edition",
    category: "Social Sciences",
    shelf: "SOC-A2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductiontoSociology3e-OP.pdf",
    description: "Introduction to sociological perspectives, research methods, culture, social stratification, and institutions.",
  },
  {
    isbn: "978-1-947172-82-1",
    title: "American Government 3e",
    author: "Glen Krutz, Sylvie Waskiewicz",
    publisher: "OpenStax / Rice University",
    year: 2021,
    edition: "3rd Edition",
    category: "Social Sciences",
    shelf: "SOC-B1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/AmericanGovernment3e-OP.pdf",
    description: "Comprehensive introduction to American government — Constitution, branches, civil liberties, public policy.",
  },
  {
    isbn: "978-1-947172-79-1",
    title: "Organizational Behavior",
    author: "J. Stewart Black, David S. Bright, Donald G. Gardner",
    publisher: "OpenStax / Rice University",
    year: 2019,
    edition: "1st Edition",
    category: "Social Sciences",
    shelf: "SOC-B2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/OrganizationalBehavior-OP.pdf",
    description: "Examination of individual, group, and organizational dynamics in the workplace — motivation, leadership, culture.",
  },
  {
    isbn: "978-1-947172-69-2",
    title: "U.S. History",
    author: "P. Scott Corbett, Volker Janssen, John M. Lund",
    publisher: "OpenStax / Rice University",
    year: 2014,
    edition: "1st Edition",
    category: "Social Sciences",
    shelf: "SOC-C1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/USHistory-OP.pdf",
    description: "Comprehensive U.S. history from pre-Columbian era to the 21st century, covering political, social, and cultural developments.",
  },

  // ============================================================
  // HUMANITIES (4)
  // ============================================================
  {
    isbn: "978-1-947172-83-8",
    title: "Introduction to Philosophy",
    author: "Nathan Smith",
    publisher: "OpenStax / Rice University",
    year: 2022,
    edition: "1st Edition",
    category: "Humanities",
    shelf: "HUM-A1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductionPhilosophy-OP.pdf",
    description: "Comprehensive introduction to philosophical inquiry — logic, metaphysics, epistemology, ethics, and political philosophy.",
  },
  {
    isbn: "978-1-947172-84-5",
    title: "Writing Guide with Handbook",
    author: "Michelle Bachelor Robinson, Maria Jerskey",
    publisher: "OpenStax / Rice University",
    year: 2021,
    edition: "1st Edition",
    category: "Humanities",
    shelf: "HUM-B1",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/WritingGuide-OP.pdf",
    description: "Comprehensive college writing guide covering academic writing, research, argumentation, and grammar.",
  },
  {
    isbn: "978-1-947172-85-2",
    title: "World History Volume 1: to 1500",
    author: "Ann Kordas, Ryan J. Lynch, Brooke Nelson",
    publisher: "OpenStax / Rice University",
    year: 2023,
    edition: "1st Edition",
    category: "Humanities",
    shelf: "HUM-B2",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/WorldHistoryVolume1-OP.pdf",
    description: "Global history from prehistory to 1500 CE covering civilizations, trade networks, religions, and cultural exchange.",
  },
  {
    isbn: "978-1-947172-86-9",
    title: "World History Volume 2: from 1400",
    author: "Ann Kordas, Ryan J. Lynch, Brooke Nelson",
    publisher: "OpenStax / Rice University",
    year: 2023,
    edition: "1st Edition",
    category: "Humanities",
    shelf: "HUM-B3",
    pdfUrl: "https://assets.openstax.org/oscms-prodcms/media/documents/WorldHistoryVolume2-OP.pdf",
    description: "Global history from 1400 to the present covering colonialism, revolutions, world wars, and globalization.",
  },
]
